// Given two strings s and t which consist of only lowercase letters.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Find the letter that was added in t.

// Example:

// Input:
// s = "abcd"
// t = "abcde"

// Output:
// e

// Explanation:
// 'e' is the letter that was added.

// solution: xor

class Solution {
public:
    char findTheDifference(string s, string t) {
        char x = 0;
    
        for (auto ch : s) {
            x ^= ch;
        }
    
        for (auto ch: t) {
            x ^= ch;
        }
    
        return x;
    }
};